name: Scala CI

on: [push, pull_request]

jobs:
  mill_tasks:
    strategy:
      matrix:
        command:
          - __.checkFormat
          - __.test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up OpenJDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache Coursier cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/coursier
          key: ${{ runner.os }}-coursier-cache-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-coursier-cache-

      - name: Run `./mill ${{ matrix.command }}`
        run: ./mill ${{ matrix.command }}
